export const BookCollectionTypes = {
  ADD_BOOK_TO_COLLECTION: 'ADD_BOOK_TO_COLLECTION',
  REMOVE_BOOK_FROM_COLLECTION: 'REMOVE_BOOK_FROM_COLLECTION',
  ADD_BOOKS_TO_COLLECTION: 'ADD_BOOKS_TO_COLLECTION',
  ADD_BOOK_TO_COLLECTIONS: 'ADD_BOOK_TO_COLLECTIONS',
};
