export const BookActionTypes = {
  SAVE_BOOK: 'SAVE_BOOK',
  REMOVE_BOOK: 'REMOVE_BOOK',
  MARK_BOOK_AS_DONE: 'MARK_BOOK_AS_DONE',
  MARK_BOOK_AS_UNDONE: 'MARK_BOOK_AS_UNDONE',
  CHANGE_BOOK_STATUS: 'CHANGE_BOOK_STATUS',
};
